---

- name: Ensure that directory Frontend project directory is present
  file:
    path: "{{ web_ui_project_dir }}"
    state: directory
    owner: "{{ web_ui_user }}"
    group: "{{ irma_server_group }}"
    mode: 02750
    recurse: "{{ vagrant_share|default(false) }}"

- name: Ensure that www-data can access IRMA files and certificates
  user:
    name: www-data
    groups: "{{ irma_server_group }},{{ irma_cert_group }}"
    append: yes

# vim: sw=2
