---

- name: Update configuration using user informations
  ini_file:
    dest: /etc/supervisor/supervisord.conf
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items: "{{supervisor_extra_confs}}"
  notify: Restart Supervisor

# vim: sw=2
