---

- name: Ensure good rights on IRMA-Probe install directory
  file:
    path: "{{ probe_project_dir }}"
    state: directory
    owner: "{{ probe_user }}"
    group: "{{ irma_server_group }}"
    mode: 02750
    recurse: "{{ vagrant_share|default(false) }}"

# vim: sw=2
