---

# As the repositories are not cloned yet, we cannot use requirements.txt
- name: "Installing dependencies with pip system-wide"
  pip:
    name: "{{ item }}"
    state: "latest"
    extra_args: "{{ pip_extra_args | default('') }}"
  with_items:
    - virustotal-api
