---

- name: Determine remote_tmp variable
  raw: echo '%TEMP%'
  register: echo_temp

- set_fact:
    remote_tmp: '{{ echo_temp.stdout[1:-3] | regex_replace("\\\\", "/") }}'

- name: Installing Chocolatey Packages Dependencies
  raw: choco.exe install "{{ item.name }}" -Version "{{ item.version }}" -y
  register: result
  failed_when: "result.rc not in {{ item.rc | default([0]) }}"
  with_items:
    - name: 7zip
      version: "9.22.01.20130618"
      rc: [0, 1]

- name: Upload Chocolatey package
  win_copy:
    src: "{{ item }}"
    dest: "{{ remote_tmp }}/"
    state: directory
  with_items:
    - ../../files/PyWin32
  register: upload_result
  ignore_errors: yes

# NOTE: known bug: it fails the first time with a stack overflow exception,
# and runs smoothly the second time
- name: Upload Chocolatey package
  win_copy:
    src: "{{ item }}"
    dest: "{{ remote_tmp }}/"
    state: directory
  with_items:
    - ../../files/PyWin32
  when: upload_result | failed

- name: Install packages
  raw: >
    cd "{{ remote_tmp }}/{{ item }}" &&
    choco.exe pack &&
    choco.exe install "{{ item }}" -source "{{ remote_tmp }}/{{ item }}" -force -y
  with_items:
    - PyWin32

- name: Remove package scripts
  win_file: 
    name: "{{ remote_tmp }}/{{ item }}"
    state: absent
  with_items:
    - PyWin32
