---

- name: F-Secure | Download Package
  get_url:
    url: "{{ fsecure_url }}"
    dest: "{{ fsecure_temp_dir }}/fsls.tar.gz"

- name: F-Secure | Extract installer
  command: tar xzf "{{ fsecure_temp_dir }}/fsls.tar.gz"
  args:
    chdir: "{{ fsecure_temp_dir }}/"

- name: F-Secure | Run installer
  shell: sh "{{ fsecure_temp_dir }}/fsls-10.20.358-rtm/f-secure-linux-security-10.20.358" --auto standalone lang=en noremotewui nolocallogin
  sudo: true

- name: F-Secure | Disable Web Interface and Firewall with fschooser
  shell: printf "f\nw\n\n" | /opt/f-secure/fsav/sbin/fschooser
  sudo: true
