---

- include: linux/provisioning_probe.yml
  when: "ansible_distribution in ['Debian', 'Ubuntu']"

- include: windows/provisioning_probe.yml
  when: "'Windows' in ansible_distribution"

# vim: sw=2
