---

- name: VBA32 | Adding i386 repositories
  shell: dpkg --add-architecture i386
  sudo: yes

- name: VBA32 | Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  sudo: yes
  with_items:
    - libc6-i386
    - libstdc++6

- name: VBA32 | Check version
  command: /opt/vba/vbacl/vbacl
  args:
    chdir: /opt/vba/vbacl
  ignore_errors: yes
  register: virusblokada_present

- include: install.yml
  when: virusblokada_present | failed

# vbaupd segfaults if IPv6 addresses are present in /etc/hosts
# when docker is used, cannot copy or move file to /etc/hosts, but shell redirections work
- name: VBA32 | Update definition files
  shell: /opt/vba/vbacl/vbaupdx "{{ virusblokada_update_url }}"
  args:
    chdir: /opt/vba/vbacl
  sudo: yes
