---

- include: debian_install_packages.yml
  when: "ansible_distribution == 'Debian' or 'docker' in group_names"

- name: Checking installed version of npm
  shell: /usr/bin/test "$(npm -v 2> /dev/null)" = {{ nodejs_npm_version }}
  register: npm_wanted_version_installed
  ignore_errors: True
  changed_when: "npm_wanted_version_installed.rc == 1"

- include: npm_compile.yml
  when: npm_wanted_version_installed.rc == 1
