---

- name: Sophos | Installation will proceed
  debug:
    msg: "Sophos is going to be installed."

- name: Sophos | Create temporary work dir
  file:
    path: "{{ sophos_temp_dir }}/"
    state: directory

- name: Sophos | Copy installation archive
  copy:
    src: "{{ sophos_archive_name }}"
    dest: "{{ sophos_temp_dir }}/{{ sophos_archive_name }}"

- name: Sophos | Dezip archive
  command: tar zxf "{{ sophos_temp_dir }}/{{ sophos_archive_name }}" -C "{{ sophos_temp_dir }}"

- name: Sophos | Launch install script
  command: "{{ sophos_temp_dir }}/sophos-av/install.sh {{ sophos_install_dir }} --acceptlicence --autostart=False --enableOnBoot=False --automatic --ignore-existing-installation"

- name: Sophos | Set parameters
  command: "{{ sophos_install_dir }}/bin/savconfig set {{ item.key }} {{ item.value }}"
  with_items:
    - { key: 'EnableOnStart', value: 'false' }

- name: Sophos | Remove temporary work dir
  file:
    path: "{{ sophos_temp_dir }}/"
    state: absent
