---

- name: Sophos | Check installed version
  command: /opt/sophos-av/bin/savscan --version
  ignore_errors: yes
  register: sophos_present

- name: Sophos | Installation already done
  debug:
    msg: "Sophos is already installed. Skipping the installation part..."
  when: sophos_present | success

- name: Sophos | Installation can not proceed
  debug:
    msg: "Sophos won't be installed because you have not provided an archive name ('sophos_archive_name' variable)."
  when: (sophos_present | failed) and not sophos_archive_name

- include: install.yml
  when: (sophos_present | failed) and sophos_archive_name

- name: Sophos | Updates won't be installed
  debug:
    msg: "Updates can not be installed because of missing information ('sophos_update_username' and/or 'sophos_update_password' variables)."
  when: ((sophos_present | success) or ((sophos_present | failed) and sophos_archive_name)) and not (sophos_update_username and sophos_update_password)

- include: update.yml
  when: ((sophos_present | success) or ((sophos_present | failed) and sophos_archive_name)) and (sophos_update_username and sophos_update_password)
