---

- name: Install sphinx in a virtualenv
  pip:
    name: sphinx
    virtualenv: "{{ probe_deployment_dir }}/venv"

- name: Build documentation
  command: "{{ probe_deployment_dir }}/venv/bin/sphinx-build -b html -d _build/doctrees . _build/html"
  args:
    chdir: "{{ probe_deployment_dir }}/docs"
    creates: "{{ probe_deployment_dir }}/docs/_build/html"
