---

- name: Clone documentation repository
  git:
    repo: "{{ frontend_documentation_deployment_repository }}"
    dest: "{{ frontend_deployment_dir }}/docs"
    version: "{{ irma_deployment_code_version }}"
    accept_hostkey: yes
  when: irma_deployment_code_version != 'local'

- name: Install sphinx in a virtualenv
  pip:
    name: sphinx
    virtualenv: "{{ frontend_deployment_dir }}/venv"
    extra_args: "{{ pip_extra_args | default('') }}"

- name: Build documentation
  command: "../venv/bin/sphinx-build -b html -d _build/doctrees . _build/html"
  args:
    chdir: "{{ frontend_deployment_dir }}/docs"
    creates: "{{ frontend_deployment_dir }}/docs/_build/html"
