---

- set_fact:
    frontend_deployment_dir: "{{ frontend_project_dir }}/{{ 'current' if irma_deployment_code_version == 'local' else 'releases/' + irma_deployment_release_name }}"

- name: Ensure that releases directory has been created
  file:
    path: "{{ frontend_project_dir }}/releases"
    state: directory

- name: Clone repository
  git:
    repo: "{{ frontend_deployment_repository }}"
    dest: "{{ frontend_deployment_dir }}"
    version: "{{ irma_deployment_code_version }}"
    accept_hostkey: yes
  when: irma_deployment_code_version != 'local'

- name: Install requirements in a Frontend virtualenv
  pip:
    requirements: "{{ frontend_deployment_dir }}/requirements.txt"
    virtualenv: "{{ frontend_deployment_dir }}/venv"
    virtualenv_site_packages: yes
    extra_args: "{{ pip_extra_args | default('') }}"

#- name: Copy previous Npm files
  #shell: "cp -R {{frontend_install_dir}}/web/node_modules {{frontend_deployment_dir}}/web/node_modules"
  #args:
    #remotes: "{{frontend_install_dir}}/web/node_modules"
    #creates: "{{frontend_deployment_dir}}/web/node_modules"
  ## Errors when current does not exists (first deployment)
  #ignore_errors: yes

#- name: Install NPM dependencies
  #npm:
    #path: "{{ frontend_deployment_dir }}/web"
    #production: "{{ irma_environment == 'production' }}"
    #ignore_scripts: yes
    #state: latest

#- name: Copy previous Bower files
  #shell: "cp -R {{frontend_install_dir}}/web/app/components {{frontend_deployment_dir}}/web/app/components"
  #args:
    #remotes: "{{frontend_install_dir}}/web/app/components"
    #creates: "{{frontend_deployment_dir}}/web/app/components"
  ## Errors when current does not exists (first deployment)
  #ignore_errors: yes

#- name: Install Bower dependencies
  #command: node_modules/.bin/bower install --config.interactive=false
  #args:
    #chdir: "{{ frontend_deployment_dir }}/web"

#- name: Generate Web Frontend
  #command: node_modules/.bin/gulp dist
  #args:
    #chdir: "{{ frontend_deployment_dir }}/web"

- name: Configure config/frontend.ini file
  ini_file:
    dest: "{{ frontend_deployment_dir }}/config/frontend.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: frontend_deployment_configs

- name: Generate documentation for frontend
  include: documentation.yml
  when: "'frontend-demo' in group_names"

- name: Create symlink release -> current
  file:
    src: "{{ frontend_deployment_dir }}"
    dest: "{{ frontend_install_dir }}"
    state: link
  when: irma_deployment_code_version != 'local'

- name: Restart Supervisor services
  supervisorctl:
    name: "{{ item.name }}"
    state: restarted
  sudo: yes
  with_items: supervisor_programs_frontend

- name: Restart Init.d services
  service:
    name: "{{ item }}"
    state: restarted
  sudo: yes
  with_items:
    - nginx

# vim: sw=2
