---

- name: BitDefender | Check version
  command: bdscan --version
  ignore_errors: yes
  register: bitdefender_present

- include: install.yml
  when: bitdefender_present | failed

- name: BitDefender | Change license key
  replace:
    dest: /opt/BitDefender-scanner/etc/bdscan.conf
    regexp: '^Key =(.*)$'
    replace: 'Key = {{ bitdefender_scanner_key }}'
  when: bitdefender_scanner_key is defined
  sudo: yes

- name: BitDefender | Download latest definition files
  command: echo "accept" | bdscan --update
